#!/usr/bin/python

import os
import io
import shutil


files=[]


for x in os.listdir('.'):
    files.append(x)
print("number of files found : %i" % len(files))
for f in files:
    org=f
    t=f.split('.')
    e=[]
    e.append(t[0])
    for m in range(1,len(t)):
       t[m]=t[m].lower()
       e.append(t[m])
    out=('.').join(e)
    shutil.move(org, 'tmp.tmp')
    shutil.move('tmp.tmp', out)
